export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#5d2500',
        'on-background': '#111c2c',
        'primary-fixed-dim': '#adc7f7',
        'on-tertiary-container': '#f57d32',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-container-low': '#f0f3ff',
        'secondary': '#13696a',
        'surface-tint': '#455f88',
        'inverse-primary': '#adc7f7',
        'on-primary-fixed': '#001b3c',
        'surface-container-highest': '#d8e3fa',
        'secondary-fixed-dim': '#89d3d4',
        'on-primary-container': '#86a0cd',
        'on-surface': '#111c2c',
        'secondary-container': '#a2eded',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#331100',
        'tertiary-fixed-dim': '#ffb68f',
        'secondary-fixed': '#a5eff0',
        'inverse-on-surface': '#ebf1ff',
        'outline-variant': '#c4c6cf',
        'on-secondary-fixed-variant': '#004f50',
        'surface-variant': '#d8e3fa',
        'error': '#ba1a1a',
        'tertiary-fixed': '#ffdbca',
        'on-error': '#ffffff',
        'background': '#f9f9ff',
        'surface-dim': '#cfdaf1',
        'inverse-surface': '#263142',
        'on-surface-variant': '#43474e',
        'on-secondary-fixed': '#002020',
        'tertiary': '#3b1500',
        'surface-container': '#e7eeff',
        'primary-container': '#1a365d',
        'on-error-container': '#93000a',
        'primary-fixed': '#d6e3ff',
        'on-tertiary-fixed-variant': '#773200',
        'on-secondary': '#ffffff',
        'surface': '#f9f9ff',
        'surface-container-high': '#dee8ff',
        'surface-bright': '#f9f9ff',
        'primary': '#002045',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#1a6d6e',
        'on-primary-fixed-variant': '#2d476f',
        'outline': '#74777f',
      },
    },
  },
  plugins: [],
}
