/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#5d2500",
        "on-background": "#111c2c",
        "primary-fixed-dim": "#adc7f7",
        "on-tertiary-container": "#f57d32",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-low": "#f0f3ff",
        "secondary": "#13696a",
        "surface-tint": "#455f88",
        "inverse-primary": "#adc7f7",
        "on-primary-fixed": "#001b3c",
        "surface-container-highest": "#d8e3fa",
        "secondary-fixed-dim": "#89d3d4",
        "on-primary-container": "#86a0cd",
        "on-surface": "#111c2c",
        "secondary-container": "#a2eded",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#331100",
        "tertiary-fixed-dim": "#ffb68f",
        "secondary-fixed": "#a5eff0",
        "inverse-on-surface": "#ebf1ff",
        "outline-variant": "#c4c6cf",
        "on-secondary-fixed-variant": "#004f50",
        "surface-variant": "#d8e3fa",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdbca",
        "on-error": "#ffffff",
        "background": "#f9f9ff",
        "surface-dim": "#cfdaf1",
        "inverse-surface": "#263142",
        "on-surface-variant": "#43474e",
        "on-secondary-fixed": "#002020",
        "tertiary": "#3b1500",
        "surface-container": "#e7eeff",
        "primary-container": "#1a365d",
        "on-error-container": "#93000a",
        "primary-fixed": "#d6e3ff",
        "on-tertiary-fixed-variant": "#773200",
        "on-secondary": "#ffffff",
        "surface": "#f9f9ff",
        "surface-container-high": "#dee8ff",
        "surface-bright": "#f9f9ff",
        "primary": "#002045",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#1a6d6e",
        "on-primary-fixed-variant": "#2d476f",
        "outline": "#74777f"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "unit": "8px",
        "section-padding": "80px",
        "stack-md": "24px",
        "gutter": "24px",
        "container-max": "1120px",
        "stack-lg": "48px"
      },
      fontFamily: {
        "h1": ["Work Sans", "sans-serif"],
        "button": ["Work Sans", "sans-serif"],
        "body-ui": ["Work Sans", "sans-serif"],
        "label-caps": ["Work Sans", "sans-serif"],
        "h3": ["Work Sans", "sans-serif"],
        "body-reading": ["Newsreader", "serif"],
        "h2": ["Work Sans", "sans-serif"]
      },
      fontSize: {
        "h1": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "button": ["16px", { lineHeight: "1", fontWeight: "500" }],
        "body-ui": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "h3": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-reading": ["20px", { lineHeight: "1.7", fontWeight: "400" }],
        "h2": ["32px", { lineHeight: "1.3", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
