from flask import Blueprint, render_template, jsonify, make_response, current_app, request
from jinja2 import TemplateNotFound
from typing import Callable

main_bp = Blueprint('main', __name__, template_folder='templates')


def _apply_security_headers(response):
    """
    Apply a conservative set of HTTP security headers following OWASP recommendations.
    Adjust policies as product requirements evolve.
    """
    # Content Security Policy: restrict resources to same origin and data URIs for images
    csp = (
        "default-src 'self'; "
        "script-src 'self'; "
        "style-src 'self'; "
        "img-src 'self' data:; "
        "font-src 'self'; "
        "connect-src 'self'; "
        "object-src 'none'; "
        "base-uri 'self'; "
        "frame-ancestors 'none';"
    )

    headers = {
        'Content-Security-Policy': csp,
        'X-Content-Type-Options': 'nosniff',
        'X-Frame-Options': 'DENY',
        'Referrer-Policy': 'strict-origin-when-cross-origin',
        # Permissions-Policy (formerly Feature-Policy): disable powerful features by default
        'Permissions-Policy': 'geolocation=(), microphone=(), camera=()',
        # Encourage secure transport; safe to include but has effect only on HTTPS
        'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
    }

    for k, v in headers.items():
        # Do not overwrite headers set elsewhere unless necessary
        if k not in response.headers:
            response.headers[k] = v

    # Ensure content type charset for HTML responses
    if response.content_type and response.content_type.startswith('text/html'):
        response.headers.setdefault('X-XSS-Protection', '0')  # modern browsers ignore; CSP handles XSS
    return response


@main_bp.after_app_request
def _after_app_request(response):
    """
    Hook to apply security headers to every response generated by the app.
    Using after_app_request ensures headers are applied even if other blueprints return responses.
    """
    try:
        return _apply_security_headers(response)
    except Exception as exc:  # pragma: no cover - very defensive
        current_app.logger.exception("Failed to apply security headers: %s", exc)
        return response


@main_bp.route('/', methods=['GET'])
def index():
    """
    Landing page route.

    Renders app/templates/index.html with a safe title variable supplied.
    Any template errors are logged and a generic error page is returned to avoid information leakage.
    """
    title = 'English Study Hub'
    try:
        rendered = render_template('index.html', title=title)
        response = make_response(rendered, 200)
        response.headers['Content-Type'] = 'text/html; charset=utf-8'
        return response
    except TemplateNotFound:
        current_app.logger.exception("Template 'index.html' not found when handling %s", request.path)
        # Return minimal generic page without exposing filesystem structure
        fallback = "<!doctype html><html><head><meta charset='utf-8'><title>Server Error</title></head>" \
                   "<body><h1>500 Internal Server Error</h1><p>Required template not found.</p></body></html>"
        return make_response(fallback, 500)
    except Exception as exc:
        current_app.logger.exception("Unhandled exception while rendering index: %s", exc)
        # Generic error response; prefer HTML if client accepts it, otherwise JSON
        accept = request.headers.get('Accept', '')
        if 'application/json' in accept:
            payload = {'error': 'internal_server_error', 'message': 'An unexpected error occurred.'}
            return make_response(jsonify(payload), 500)
        fallback = "<!doctype html><html><head><meta charset='utf-8'><title>Server Error</title></head>" \
                   "<body><h1>500 Internal Server Error</h1><p>An unexpected error occurred.</p></body></html>"
        return make_response(fallback, 500)


@main_bp.route('/health', methods=['GET'])
def health():
    """
    Lightweight health check endpoint suitable for load balancers and orchestration systems.

    Returns:
        JSON { "status": "ok" } with HTTP 200 when the process is healthy.
    """
    try:
        payload = {'status': 'ok'}
        response = make_response(jsonify(payload), 200)
        # Prevent caching of the health response to ensure clients always check current status
        response.headers['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
        return response
    except Exception as exc:  # pragma: no cover - defensive
        current_app.logger.exception("Health check failed: %s", exc)
        return make_response(jsonify({'status': 'error'}), 500)


@main_bp.app_errorhandler(500)
def _handle_internal_server_error(error):
    """
    Centralized handler for uncaught 500 errors raised within this blueprint's context.
    Provides a safe, generic response and logs the original exception.
    """
    current_app.logger.exception("Internal Server Error: %s", error)
    accept = request.headers.get('Accept', '')
    if 'application/json' in accept:
        return make_response(jsonify({'error': 'internal_server_error'}), 500)
    html = "<!doctype html><html><head><meta charset='utf-8'><title>Error</title></head>" \
           "<body><h1>500 Internal Server Error</h1><p>Please contact support.</p></body></html>"
    resp = make_response(html, 500)
    resp.headers['Content-Type'] = 'text/html; charset=utf-8'
    return resp